spring.datasource.url=jdbc:mysql://localhost:3306/handmade2?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# \u30c9\u30e1\u30a4\u30f3\u8a18\u8ff0\u306e\u77ed\u7e2e(\uff5e.app.entity\u307e\u3067\u3092\u7701\u7565)
mybatis.type-aliases-package=com.example.app.dto
# MyBatis XML\u306e\u8aad\u307f\u8fbc\u307f
mybatis.mapper-locations=classpath:/mappers/*.xml

mybatis.configuration.map-underscore-to-camel-case=true